export const maharashtraData = {
  districts: [
    {
      name: "Ahmadnagar",
      villages: [
        "Akole",
        "Jamkhed",
        "Karjat",
        "Kopargaon",
        "Nagar",
        "Nevasa",
        "Parner",
        "Pathardi",
        "Rahata",
        "Rahuri",
        "Sangamner",
        "Shevgaon",
        "Shrigonda",
        "Shrirampur",
      ],
    },
    { name: "Akola", villages: ["Akola", "Akot", "Balapur", "Barshitakli", "Murtizapur", "Patur", "Telhara"] },
    {
      name: "Amravati",
      villages: [
        "Achalpur",
        "Amravati",
        "Anjangaon",
        "Bhatkuli",
        "Chandur Bazar",
        "Chandur Railway",
        "Chikhaldara",
        "Daryapur",
        "Dharni",
        "Dhamangaon",
        "Morshi",
        "Nandgaon",
        "Teosa",
        "Warud",
      ],
    },
    {
      name: "Aurangabad",
      villages: [
        "Aurangabad",
        "Gangapur",
        "Kannad",
        "Khultabad",
        "Paithan",
        "Phulambri",
        "Sillod",
        "Soegaon",
        "Vaijapur",
      ],
    },
    { name: "Bhandara", villages: ["Bhandara", "Lakhani", "Mohadi", "Pauni", "Sakoli", "Tumsar"] },
    {
      name: "Bid",
      villages: [
        "Ambejogai",
        "Ashti",
        "Bid",
        "Dharur",
        "Georai",
        "Kaij",
        "Majalgaon",
        "Parli",
        "Patoda",
        "Shirur-Kasar",
        "Wadwani",
      ],
    },
    {
      name: "Buldana",
      villages: [
        "Buldana",
        "Chikhli",
        "Deulgaon Raja",
        "Jalgaon Jamod",
        "Khamgaon",
        "Lonar",
        "Malkapur",
        "Mehkar",
        "Motala",
        "Nandura",
        "Sangrampur",
        "Shegaon",
        "Sindkhed Raja",
      ],
    },
    {
      name: "Chandrapur",
      villages: [
        "Ballarpur",
        "Bhadravati",
        "Brahmapuri",
        "Chandrapur",
        "Chimur",
        "Gondpipri",
        "Jivati",
        "Korpana",
        "Mul",
        "Nagbhir",
        "Pombhurna",
        "Rajura",
        "Saoli",
        "Sindewahi",
        "Warora",
      ],
    },
    { name: "Dhule", villages: ["Dhule", "Sakri", "Shindkheda", "Shirpur"] },
    {
      name: "Gadchiroli",
      villages: [
        "Aheri",
        "Armori",
        "Bhamragad",
        "Chamorshi",
        "Desaiganj",
        "Dhanora",
        "Etapalli",
        "Gadchiroli",
        "Korchi",
        "Kurkheda",
        "Mulchera",
        "Sironcha",
      ],
    },
    {
      name: "Gondiya",
      villages: ["Amgaon", "Arjuni Morgaon", "Deori", "Goregaon", "Gondiya", "Sadak Arjuni", "Salekasa", "Tirora"],
    },
    { name: "Hingoli", villages: ["Aundha Nagnath", "Basmath", "Hingoli", "Kalamnuri", "Sengaon"] },
    {
      name: "Jalgaon",
      villages: [
        "Amalner",
        "Bhadgaon",
        "Bhusawal",
        "Bodwad",
        "Chalisgaon",
        "Chopda",
        "Dharangaon",
        "Erandol",
        "Jalgaon",
        "Jamner",
        "Muktainagar",
        "Pachora",
        "Parola",
        "Raver",
        "Yawal",
      ],
    },
    {
      name: "Jalna",
      villages: ["Ambad", "Badnapur", "Bhokardan", "Ghansawangi", "Jafferabad", "Jalna", "Mantha", "Partur"],
    },
    {
      name: "Kolhapur",
      villages: [
        "Ajra",
        "Bavda",
        "Bhudargad",
        "Chandgad",
        "Gaganbawada",
        "Gadhinglaj",
        "Hatkanangle",
        "Kagal",
        "Karvir",
        "Panhala",
        "Radhanagari",
        "Shahuwadi",
      ],
    },
    {
      name: "Latur",
      villages: [
        "Ahmadpur",
        "Ausa",
        "Chakur",
        "Deoni",
        "Jalkot",
        "Latur",
        "Nilanga",
        "Renapur",
        "Shirur Anantpal",
        "Udgir",
      ],
    },
    {
      name: "Nagpur",
      villages: [
        "Bhiwapur",
        "Hingna",
        "Kalameshwar",
        "Kamptee",
        "Katol",
        "Kuhi",
        "Mauda",
        "Nagpur Rural",
        "Nagpur Urban",
        "Narkhed",
        "Parseoni",
        "Ramtek",
        "Savner",
        "Umred",
      ],
    },
    {
      name: "Nanded",
      villages: [
        "Ardhapur",
        "Bhokar",
        "Biloli",
        "Deglur",
        "Dharmabad",
        "Hadgaon",
        "Himayatnagar",
        "Kandhar",
        "Kinwat",
        "Loha",
        "Mahur",
        "Mukhed",
        "Naigaon",
        "Nanded",
        "Umri",
      ],
    },
    { name: "Nandurbar", villages: ["Akkalkuwa", "Akrani", "Nandurbar", "Nawapur", "Shahada", "Talode"] },
    {
      name: "Nashik",
      villages: [
        "Baglan",
        "Chandvad",
        "Deola",
        "Dindori",
        "Igatpuri",
        "Kalwan",
        "Malegaon",
        "Nandgaon",
        "Nashik",
        "Niphad",
        "Peth",
        "Sinnar",
        "Surgana",
        "Trimbakeshwar",
        "Yeola",
      ],
    },
    {
      name: "Osmanabad",
      villages: ["Bhum", "Kalamb", "Lohara", "Osmanabad", "Paranda", "Tuljapur", "Umarga", "Washi"],
    },
    {
      name: "Parbhani",
      villages: ["Gangakhed", "Jintur", "Manwath", "Palam", "Parbhani", "Pathri", "Purna", "Sailu", "Sonpeth"],
    },
    {
      name: "Pune",
      villages: [
        "Ambegaon",
        "Baramati",
        "Bhor",
        "Daund",
        "Haveli",
        "Indapur",
        "Junnar",
        "Khed",
        "Mawal",
        "Mulshi",
        "Pune City",
        "Purandhar",
        "Shirur",
        "Velhe",
      ],
    },
    {
      name: "Raigarh",
      villages: [
        "Alibag",
        "Karjat",
        "Khalapur",
        "Mahad",
        "Mangaon",
        "Mhasla",
        "Murud",
        "Panvel",
        "Pen",
        "Poladpur",
        "Roha",
        "Shrivardhan",
        "Sudhagad",
        "Tala",
        "Uran",
      ],
    },
    {
      name: "Ratnagiri",
      villages: ["Chiplun", "Dapoli", "Guhagar", "Khed", "Lanja", "Mandangad", "Rajapur", "Ratnagiri", "Sangameshwar"],
    },
    {
      name: "Sangli",
      villages: [
        "Atpadi",
        "Jat",
        "Kadegaon",
        "Kavathemahankal",
        "Khanapur",
        "Miraj",
        "Palus",
        "Shirala",
        "Tasgaon",
        "Walwa",
      ],
    },
    {
      name: "Satara",
      villages: [
        "Jawali",
        "Karad",
        "Khandala",
        "Khatav",
        "Koregaon",
        "Mahabaleshwar",
        "Man",
        "Patan",
        "Phaltan",
        "Satara",
        "Wai",
      ],
    },
    {
      name: "Sindhudurg",
      villages: ["Devgad", "Dodamarg", "Kankavli", "Kudal", "Malwan", "Sawantwadi", "Vaibhavvadi", "Vengurla"],
    },
    {
      name: "Solapur",
      villages: [
        "Akkalkot",
        "Barshi",
        "Karmala",
        "Madha",
        "Malshiras",
        "Mangalvedhe",
        "Mohol",
        "Pandharpur",
        "Sangole",
        "Solapur North",
        "Solapur South",
      ],
    },
    {
      name: "Thane",
      villages: [
        "Ambarnath",
        "Bhiwandi",
        "Dahanu",
        "Jawhar",
        "Kalyan",
        "Murbad",
        "Palghar",
        "Shahapur",
        "Talasari",
        "Thane",
        "Ulhasnagar",
        "Vasai",
        "Vikramgad",
      ],
    },
    {
      name: "Wardha",
      villages: ["Arvi", "Ashti", "Deoli", "Hinganghat", "Karanja", "Pulgaon", "Samudrapur", "Seloo", "Wardha"],
    },
    { name: "Washim", villages: ["Karanja", "Malegaon", "Mangrulpir", "Manora", "Risod", "Washim"] },
    {
      name: "Yavatmal",
      villages: [
        "Arni",
        "Babulgaon",
        "Darwha",
        "Digras",
        "Ghatanji",
        "Kalamb",
        "Kelapur",
        "Mahagaon",
        "Maregaon",
        "Ner",
        "Pusad",
        "Ralegaon",
        "Umarkhed",
        "Wani",
        "Yavatmal",
        "Zari-Jamani",
      ],
    },
  ],
}

export const indianStates = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
]
